# Generated by Django 5.0.4 on 2024-04-27 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField(max_length=255)),
                ('image', models.ImageField(upload_to='course_images/')),
                ('categories', models.ManyToManyField(related_name='courses', to='FcourseAPI.category')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FcourseAPI.category')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FcourseAPI.course')),
            ],
            options={
                'unique_together': {('course', 'category')},
            },
        ),
    ]
