# Generated by Django 5.0.4 on 2024-04-28 06:39

import FcourseAPI.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FcourseAPI', '0002_remove_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=FcourseAPI.models.generate_filename),
            preserve_default=False,
        ),
    ]
